name: Update gist
description: "Are you an early 🐤 or a night 🦉? Let's check out in gist"
branding:
  icon: "activity"
  color: "blue"
runs:
  using: "node16"
  main: "dist/index.js"
  GIST_ID: e5c2700e301923abad46a30a360c6b74
          TIMEZONE: Asia/Seoul
