name: Update gist
description: "Are you an early 🐤 or a night 🦉? Let's check out in gist"
branding:
  icon: "activity"
  color: "blue"
runs:
  using: "node16"
  main: "dist/index.js"
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TIMEZONE: Asia/Seoul

